Initial run
oasis-roles/users_and_groups pull request #1
Opened 2019-05-20 19:53 UTC by andrew103

The role isn't idempotent since I'm using the command module and registering the stdout to a variable. A potential workaround I thought of is grabbing all of the group/user data from the /etc/group file in pre-tasks then parsing for the user/group being manipulated... probably a bit over the top for something like this though.

2019-05-20 20:39 UTC, tehsmyers requested changes
I left a bunch of comments, but the only things that I think need changing are expanding the readme examples and fixing idempotence with the command module invocation.

2019-05-20 20:39 UTC, seandst commented on defaults/main.yml
> +# A list of users to add to specified groups. List items are formatted like so:
We've gotten into a convention where commenting up defaults/main is done sparingly, and when it is done, those comments are for the benefit of role developers, not users. So these notes about how to format yaml, and in general all the comments in here that duplicate README content, can go away if you want.

2019-05-20 20:39 UTC, seandst commented on tasks/remove_users.yaml
> +  command: groups {{ item['name'] }}
You can regain idempotence with a `changed_when: false` here, which should also allow removing the admonition about idempotence from the README.

2019-05-20 20:39 UTC, seandst commented on tasks/remove_users.yaml
> +    current_groups: "{{ current_groups.stdout.split(' : ')[1].split() }}"
This appears platform dependent, on my system the only thing in stdout is a space-separated list of groups, no colons. I don't know if this is something to be concerned about though.

2019-05-20 20:39 UTC, seandst commented on tasks/main.yml
> +- name: Add users to groups
This task could potentially create a user. Do we want to support more of the `user` module's parameters to better facilitate user creation, or would it be a better idea to mention in the README that this role is expected to work only on existing users?

2019-05-20 20:44 UTC, seandst commented
Also, I wonder if all the openstack scenario boilerplate could potentially go away, since I hope/expect all testing scenarios could be done in docker.

2019-05-20 21:39 UTC, andrew103 commented on tasks/remove_users.yaml
> +    current_groups: "{{ current_groups.stdout.split(' : ')[1].split() }}"
Did you run `groups <username>`? Running `groups` on its own gives that behavior as it retrieves the groups of the user running the command.

2019-05-20 23:50 UTC, seandst commented on tasks/remove_users.yaml
> +    current_groups: "{{ current_groups.stdout.split(' : ')[1].split() }}"
Yeah, the output is the same whether a user is targeted or not. All that matters is that it works on the platforms advertised in meta/main, though, which mine most definitely is not, so I don't know how much, if at all, we might need to worry about this.

2019-05-21 03:10 UTC, greg-hellings requested changes

2019-05-21 03:10 UTC, greg-hellings commented on README.md
> +      - {name: "john_doe", groups: ["new_group1", "new_group2"]}
Why JSON syntax?

2019-05-21 03:10 UTC, greg-hellings commented on tasks/main.yml
> +- include_tasks: remove_users.yaml
It doesn't feel like `remove_users.yml` actually is removing users. It feels more like it's doing some crazy logic to pare down a user's groups. I'm not sure why, though. If we want the call to this role to leave the user in ONLY the specified roles, then why not just change line 14 to `false`?

Basically I'm confused. It looks like I can use this role, currently, to:
* add groups to the host
* add users to the host
* add users to groups
* remove users from groups
* remove groups

But I can't actually remove users?

2019-05-21 15:53 UTC, andrew103 commented on tasks/remove_users.yaml
> +    current_groups: "{{ current_groups.stdout.split(' : ')[1].split() }}"
I see. Out of curiosity what are you running?

2019-05-21 16:17 UTC, andrew103 commented on tasks/main.yml
> +- include_tasks: remove_users.yaml
Good point. I'll add the functionality and rename some stuff to be more clear.

With regard to line 14 being `true`, my thought was that if an admin was altering group permissions of an existing user, I didn't want to make them figure out which groups the user was already a member of in order to not mistakenly remove the user from those groups.

2019-05-21 16:18 UTC, andrew103 commented on tasks/main.yml
> +- name: Add users to groups
Probably a good idea to implement that. I'll add the support and make it more clear.

2019-05-21 16:20 UTC, andrew103 commented on README.md
> +      - {name: "john_doe", groups: ["new_group1", "new_group2"]}
I thought it looked a bit cleaner. Also more concise for large changes since it's one line versus 3+ per entry. I can see how it's a bit out of place though in terms of formatting.

2019-05-23 20:33 UTC, robled commented on tasks/remove_group_members.yaml
> +  command: groups {{ item['name'] }}
Here's a convoluted way to do this in native Ansible:

```
- hosts: localhost
  gather_facts: false
  vars:
    my_user: robled
  tasks:
    - getent:
        database: group
      register: all_groups

    - set_fact:
        my_users_groups: []

    - set_fact:
        my_users_groups: "{{ my_users_groups + [item.key] }}"
      with_dict: "{{ all_groups.ansible_facts['getent_group'] }}"
      when: "my_user in item.value"

    - debug:
        msg: "{{ my_users_groups }}"
```

Not really sure this is any better.  Part of the problem is that an [Ansible bug](https://github.com/ansible/ansible/issues/38075) prevents looping with **set_fact**.

2019-05-23 21:08 UTC, seandst commented on tasks/remove_group_members.yaml
> +  command: groups {{ item['name'] }}
That doesn't take into account the user's primary group in passwd. Using my system as an example, this would have unexpectedly removed me from my primary group `semyers`, as I'm not actually a member of the `semyers` group according to the group database alone.

2019-05-23 21:10 UTC, seandst commented on tasks/remove_users.yaml
> +    current_groups: "{{ current_groups.stdout.split(' : ')[1].split() }}"
That'd be ![Arch Linux!](https://www.archlinux.org/static/logos/archlinux-logo-dark-1200dpi.b42bd35d5916.png)

2019-05-23 21:10 UTC, robled commented on tasks/remove_group_members.yaml
> +  command: groups {{ item['name'] }}
Apparently the `id` command gives us the user's primary group in a fairly simple way:

```
- hosts: localhost
  gather_facts: false
  vars:
    my_user: robled
  tasks:
    - command: id -Gn {{ my_user }}
      changed_when: false
      register: all_groups

    - set_fact:
        my_users_groups: "{{ (my_users_groups | default([])) + [item] }}"
      with_items: "{{ all_groups.stdout.split(' ') }}"

    - debug:
        msg: "{{ item }}"
      with_items: "{{ my_users_groups }}"
```

2019-05-23 21:14 UTC, seandst commented on tasks/remove_group_members.yaml
> +  command: groups {{ item['name'] }}
I like this because you don't need to split on the colon anymore (at least, I don't think you do?), but the `all_groups.stdout.split(' ')` can probably just be `all_groups.stdout.split()` :+1: now we just need to write all this up as an ansible module or something :D

2019-05-23 21:44 UTC, andrew103 commented on tasks/remove_group_members.yaml
> +  command: groups {{ item['name'] }}
Is a `with_items` loop still necessary for the `set_fact` task though? The `id` command gives you just the groups of the user so the `set_fact` task should be able to be
```
- set_fact:
    my_users_groups: "{{ all_groups.stdout.split() }}"
```
There's no `when` statement so it would just recreate the list being looped over anyways.

2019-05-23 23:53 UTC, robled commented on tasks/remove_group_members.yaml
> +  command: groups {{ item['name'] }}
Haha, definitely not necessary.  Good catch.  I'm going back to my hole now.

2019-05-24 02:53 UTC, greg-hellings commented
I feel like this whole role is still vastly overcomplicated.

Like, why can't it just be 4 tasks:
* Groups with state: present
* Users with state: present
* Users with state: absent
* Groups with state: absent

Why all this extra group logic and tasks just for adding a user to a group when the users with state: present call can already handle those use cases?

2019-05-24 16:45 UTC, andrew103 commented
@greg-hellings The way I approached this is I initially came up with 3 different generic use cases for the role: manage groups, manage users, manage group membership. Then I figured each use case ought to have 2 tasks: one for creating/modifying the entity/entities and one for removing the entity/entities.

I had thought about putting together user management and group member management together considering they use the same module, but opted to keep them separate in favor of being explicit in what the goal of each task was. On the developer side sure this might not make any sense, but I felt it would be an improvement on the consumer side as the variable names and tasks match up with the specific "atomic" task that a user may want to perform. Overall, I tried to setup the role to be more practical for the user side.

I could also be very wrong in assuming that the current implementation is more practical for users... @seandst @robled what are your thoughts on this?

In regard to the group logic used for removing users from groups, that exists so that a user can just specify a group that they want to be removed from without having to pass in the groups they want to stay a member of. The `group` module currently doesn't have a way to remove users from specified groups. You would have to specify all the groups a user wants to retain membership of and exclude groups to be removed from in order to perform that action. The group logic makes sense for the case (albeit an extreme one) where a user is a member of, say, 500 groups but only wants to be removed from one of those groups. Instead of specifying the 499 groups they want to keep, they just specify the one they want to be removed from. Now, say they want to completely wipe their group membership and start fresh. They can still do that with the `add_membership` task by passing an empty list for `groups` and set `append: false`. This may not be obvious though so I should probably document that in the README.

2019-05-24 17:10 UTC, robled commented on tasks/remove_users.yaml
> +    current_groups: "{{ current_groups.stdout.split(' : ')[1].split() }}"
(btw)

2019-05-24 17:18 UTC, robled commented
The way I interpret @andrew103's approach here, is that the complexity stems from _management_ of users and groups as opposed to simply _adding_ users and groups to allow an application to be deployed.  If management is something we want or need, perhaps the PR as it stands is the way to go.  If we just want to do some simple "setup" tasks to get things going, then @greg-hellings idea is the way forward.

2019-05-24 19:03 UTC, greg-hellings commented
I suppose it goes back to the requirements, then. I wasn't there when requirements for this role were defined. If it's just for installation of apps, then all we need is the four basic steps I outlined as long as the user creation allows `append: true` for group membership addition.

It seems the only real complexity is in removing groups from a user, which is the only piece of functionality that the `user` module doesn't inherently support. Which begs the question - is the best way to tackle this, then, to avoid all this parsing and write a simple module to do group removal, if indeed that is a requirement of this role?

2019-05-24 19:15 UTC, andrew103 commented
I don't think any official requirements were set for this role. If anything, the initial goal was to create a role capable of replacing [these tasks](https://gitlab.cee.redhat.com/oasis-origin/rhv_hosted_engine_deploy/blob/master/site.yml#L55). From there it was open-ended.

2019-06-06 18:19 UTC, robled commented
I would argue that the official requirements were to do what the original playbook previously did, only in proper role format.  In the original playbook, the following happened (also check the "big playbook planning notes" document that we drafted for details):

```
    - name: Create kvm group
      group:
        state: present
        gid: "{{ nfs_share_group.gid }}"
        name: "{{ nfs_share_group.name }}"
    - name: Create vdsm user in kvm group
      user:
        state: present
        name: "{{ nfs_share_user.name }}"
        uid: "{{ nfs_share_user.uid }}"
        group: "{{ nfs_share_group.name }}"
```

@greg-hellings - if we want to decrease the complexity here, then we can just make this role only handle user/group additions and not removals, or we can leave it as-is.  I welcome the team's thoughts here.

2019-06-13 19:03 UTC, greg-hellings commented
I'm OK with leaving it as-is. I just wanted to understand better the complexity. Removing and restricting users down to particular group sets seems overly complicated for any typical install task, but since we have it I don't see a problem with keeping it.

If there's a problem with it later, we can either remove it at that time or move to a module-based implementation.

2019-06-13 19:03 UTC, greg-hellings approved these changes

2019-06-25 18:16 UTC, tehsmyers approved these changes
Apologies, I didn't realize this was still marked as requesting changes from me.

2019-06-25 18:19 UTC, seandst commented
The downstream tests are failing, but also unnecessary, I think. Probably just remove the Jenkinsfile and they'll go away.

2019-06-25 18:30 UTC, merged